name: CI
on: ["push", "pull_request"]

jobs:
  frontend_codequality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          # cache: "yarn"
          # cache-dependency-path: "docroot/themes/custom/drupalastic/yarn.lock"

      # - name: Frontend Code Quality
      #   run: |
      #     cd docroot/themes/custom/drupalastic
      #     yarn
      #     yarn lint
